### ISSUE TITLE
robot_skill/api bug

### ISSUE THREAD

**Issue by P-ict0** [tue-robotics/tue_robocup#1276]
```py
[ERROR][/action_server][1680178107.899194]: Exception in your execute callback: 'NoneType' object has no attribute 'encoding'
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/amigo/ros/noetic/system/src/action_server/src/action_server/server.py", line 84, in _add_action_cb
    action_result = self._task_manager.execute_next_action()
  File "/home/amigo/ros/noetic/system/src/action_server/src/action_server/task_manager.py", line 128, in execute_next_action
    result = self._active_action.start()
  File "/home/amigo/ros/noetic/system/src/action_server/src/action_server/actions/action.py", line 143, in start
    self._start()
  File "/home/amigo/ros/noetic/system/src/action_server/src/action_server/actions/point_target.py", line 26, in _start
    outcome = self._point_sm.execute()
  File "/home/amigo/ros/noetic/system/src/robot_smach_states/src/robot_smach_states/human_interaction/entity_from_operator_pose.py", line 32, in execute
    if not self._prep_operator():  # output should be checked
  File "/home/amigo/ros/noetic/system/src/robot_smach_states/src/robot_smach_states/human_interaction/entity_from_operator_pose.py", line 80, in _prep_operator
    success, found_people_ids = self._robot.ed.detect_people(*self._show_image(timeout=1))
  File "/home/amigo/ros/noetic/system/src/robot_smach_states/src/robot_smach_states/human_interaction/entity_from_operator_pose.py", line 72, in _show_image
    self._robot.hmi.show_image_from_msg(image_data[0], timeout)
  File "/home/amigo/ros/noetic/system/src/robot_skills/src/robot_skills/api.py", line 89, in show_image_from_msg
    compressed_image_msg = self.cv_bridge.cv2_to_compressed_imgmsg(self.cv_bridge.imgmsg_to_cv2(msg, "bgr8"))
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 163, in imgmsg_to_cv2
    dtype, n_channels = self.encoding_to_dtype_with_channels(img_msg.encoding)
AttributeError: 'NoneType' object has no attribute 'encoding'

```

**Comment by MatthijsBurgh** [comment]
This only happens when it wasn't able to get an image. But it should be handled in a better way with a better log message. That it wasn't able to get an image.

**Comment by MatthijsBurgh** [comment]
Output of https://github.com/tue-robotics/tue_robocup/blob/master/robot_smach_states/src/robot_smach_states/human_interaction/entity_from_operator_pose.py#L71 needs to be checked.
