### ISSUE TITLE
get_closest_entity fails when center_point=kdl.Vector()

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#183]
This bug is introducted by caa3264753fd15958c3e361d9d42cf6cdaa83a3b. See the backtrace:
```
Traceback (most recent call last):
  File "./challenge_spr/bluff_game.py", line 146, in <module>
    startup(TestBluffGame, challenge_name="challenge_spr")
  File "/home/amigo/ros/kinetic/dev/src/robot_smach_states/src/robot_smach_states/util/startup.py", line 91, in startup
    outcome = executioner.execute()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
smach.exceptions.InvalidUserCodeError: Could not execute state 'BLUFF_GAME_1' of type '<__main__.HearQuestion object at 0x7fa78d01ed10>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "./challenge_spr/bluff_game.py", line 95, in execute
    turn_to_closest_entity(self.robot)
  File "./challenge_spr/bluff_game.py", line 66, in turn_to_closest_entity
    _turn_to_closest_entity(robot)
  File "./challenge_spr/bluff_game.py", line 28, in _turn_to_closest_entity
    operator = robot.ed.get_closest_entity(radius=1.9, center_point=robot.base.get_location().p)
  File "/home/amigo/ros/kinetic/dev/src/robot_skills/src/robot_skills/world_model_ed.py", line 98, in get_closest_entity
    entities = self.get_entities(type="", center_point=center_point, radius=radius)
  File "/home/amigo/ros/kinetic/dev/src/robot_skills/src/robot_skills/world_model_ed.py", line 79, in get_entities
    self._publish_marker(center_point, radius)
  File "/home/amigo/ros/kinetic/dev/src/robot_skills/src/robot_skills/world_model_ed.py", line 376, in _publish_marker
    marker.pose.position.x = center_point.vector.x()
AttributeError: 'Vector' object has no attribute 'vector'
```

**Comment by LoyVanBeek** [comment]
Pretty sure that it wants a VectorStamped, to know in what frame the vector is defined
