### ISSUE TITLE
RIPS not talking and hearing

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#252]
[INFO] [1493887749.937588]: Robot did not hear you (timeout)
[ERROR] [1493887749.942805]: InvalidUserCodeError: Could not execute state 'HEAR' of type '<robot_smach_states.human_interaction.human_interaction.HearOptions object at 0x7fb0d1ff0050>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py", line 93, in execute
    answer = self._robot.ears.recognize("<option>", {"option":self._options}, self._timeout)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/ears.py", line 27, in recognize
    answer = self._hmi.old_query(spec, choices, timeout=time_out.to_sec())
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 28, in old_query
    return self._client.old_query(spec=spec, choices=choices, timeout=timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 136, in old_query
    return OldSpeechResponse(result="")
TypeError: __new__() takes exactly 3 arguments (2 given)

[ERROR] [1493887749.942955]: State 'ASK_CONTINUE' failed to execute.
[ERROR] [1493887749.943082]: Robot exited with <class 'smach.exceptions.InvalidUserCodeError'>,Could not execute state 'HEAR' of type '<robot_smach_states.human_interaction.human_interaction.HearOptions object at 0x7fb0d1ff0050>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py", line 93, in execute
    answer = self._robot.ears.recognize("<option>", {"option":self._options}, self._timeout)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/ears.py", line 27, in recognize
    answer = self._hmi.old_query(spec, choices, timeout=time_out.to_sec())
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 28, in old_query
    return self._client.old_query(spec=spec, choices=choices, timeout=timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 136, in old_query
    return OldSpeechResponse(result="")
TypeError: __new__() takes exactly 3 arguments (2 given)
,<traceback object at 0x7fb0d1f31e18>

**Comment by reinzor** [comment]
Grammar is empty, please provide a valid grammar

> answer = self._robot.ears.recognize("", {"option":self._options}, self._timeout)
