### ISSUE TITLE
SPR crash due to amigo.hmi.query(..., timeout) type changed

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#307]
```
[INFO] [1496176825.684661]: Calling Skybiometry...
[INFO] [1496176830.126392]: face_properties:
 - gender: 0
age: 34
 - gender: 0
age: 30
[INFO] [1496176830.126731]: 'There are 2 males and 0 females in the crowd'
[INFO] [1496176833.218495]: State machine transitioning 'DETECT_CROWD':'succeeded'-->'REQUEST_OPERATOR'
[INFO] [1496176833.218720]: 'Who wants to play riddles with me?'
[INFO] [1496176835.228961]: State machine transitioning 'REQUEST_OPERATOR':'spoken'-->'WAIT_FOR_OPERATOR'
WaitForDesignator: waiting 0/3
[ERROR] [1496176835.236500]: No entities found in 

Designator(
  center_point = [           0,           0,           0] @ /map
  center_point_designator = None
  criteriafuncs = []
  debug = False
  ed = <robot_skills.world_model_ed.ED object at 0x7f94caf967d0>
  id = 
  id_designator = None
  lockable = <bound method EdEntityDesignator.lockable of Designator(resolve_type=<class 'robot_skills.util.entity.Entity'>, name=None)>
  name = None
  radius = 0
  resolve_type = <class 'robot_skills.util.entity.Entity'>
  robot = <robot_skills.amigo.Amigo object at 0x7f94cb1d3510>
  type = human
  type_designator = None
  weight_function = <function <lambda> at 0x7f94cac29578>)


WaitForDesignator: waiting 1/3
[ERROR] [1496176836.249118]: No entities found in 

Designator(
  center_point = [           0,           0,           0] @ /map
  center_point_designator = None
  criteriafuncs = []
  debug = False
  ed = <robot_skills.world_model_ed.ED object at 0x7f94caf967d0>
  id = 
  id_designator = None
  lockable = <bound method EdEntityDesignator.lockable of Designator(resolve_type=<class 'robot_skills.util.entity.Entity'>, name=None)>
  name = None
  radius = 0
  resolve_type = <class 'robot_skills.util.entity.Entity'>
  robot = <robot_skills.amigo.Amigo object at 0x7f94cb1d3510>
  type = human
  type_designator = None
  weight_function = <function <lambda> at 0x7f94cac29578>)


WaitForDesignator: waiting 2/3
[ERROR] [1496176837.281309]: No entities found in 

Designator(
  center_point = [           0,           0,           0] @ /map
  center_point_designator = None
  criteriafuncs = []
  debug = False
  ed = <robot_skills.world_model_ed.ED object at 0x7f94caf967d0>
  id = 
  id_designator = None
  lockable = <bound method EdEntityDesignator.lockable of Designator(resolve_type=<class 'robot_skills.util.entity.Entity'>, name=None)>
  name = None
  radius = 0
  resolve_type = <class 'robot_skills.util.entity.Entity'>
  robot = <robot_skills.amigo.Amigo object at 0x7f94cb1d3510>
  type = human
  type_designator = None
  weight_function = <function <lambda> at 0x7f94cac29578>)


[INFO] [1496176838.282552]: State machine transitioning 'WAIT_FOR_OPERATOR':'failed'-->'RIDDLE_GAME_1'
[ERROR] [1496176838.289074]: InvalidUserCodeError: Could not execute state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f94cab5c690>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 180, in execute
    res = hear(self.robot, time_out=self.time_out)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 20, in hear
    return robot.hmi.query('Question?', knowledge.grammar, 'T', timeout=time_out)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 20, in query
    return self._client.query(description, grammar, target, timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 95, in query
    rospy.loginfo('Question: %s, grammar: %s, timeout: %.2f', description, _truncate(grammar), timeout)
  File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 176, in emit
    record_message = _defaultFormatter.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: float argument required, not Duration

[ERROR] [1496176838.289281]: Robot exited with <class 'smach.exceptions.InvalidUserCodeError'>,Could not execute state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f94cab5c690>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 180, in execute
    res = hear(self.robot, time_out=self.time_out)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 20, in hear
    return robot.hmi.query('Question?', knowledge.grammar, 'T', timeout=time_out)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 20, in query
    return self._client.query(description, grammar, target, timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 95, in query
    rospy.loginfo('Question: %s, grammar: %s, timeout: %.2f', description, _truncate(grammar), timeout)
  File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 176, in emit
    record_message = _defaultFormatter.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: float argument required, not Duration
,<traceback object at 0x7f94cab22758>
[INFO] [1496176838.289506]: Torso cancelling all goals on close
[INFO] [1496176838.289759]: left arm cancelling all goals on all arm-related ACs on close
[INFO] [1496176838.290062]: right arm cancelling all goals on all arm-related ACs on close
Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/challenge_spr/src/challenge_spr.py", line 207, in <module>
    startup(ChallengeSpeechPersonRecognition, challenge_name="challenge_spr")
  File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/util/startup.py", line 81, in startup
    outcome = executioner.execute()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
smach.exceptions.InvalidUserCodeError: Could not execute state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f94cab5c690>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 180, in execute
    res = hear(self.robot, time_out=self.time_out)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 20, in hear
    return robot.hmi.query('Question?', knowledge.grammar, 'T', timeout=time_out)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 20, in query
    return self._client.query(description, grammar, target, timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 95, in query
    rospy.loginfo('Question: %s, grammar: %s, timeout: %.2f', description, _truncate(grammar), timeout)
  File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 176, in emit
    record_message = _defaultFormatter.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: float argument required, not Duration
```

**Comment by MatthijsBurgh** [comment]
fixed by #319
