### ISSUE TITLE
[manipulation] Namespacing ed service in PDF generator

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#35]
[ERROR] [WallTime: 1426084825.081688] InvalidUserCodeError: Could not execute state 'EXPORT_PDF' of type '<smach.state.CBState object at 0x7ff0fc03f1d0>': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state.py", line 152, in execute
    return self._cb(ud, *self._cb_args, **self._cb_kwargs)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/util.py", line 87, in __call__
    return self._cb(*args, **kwargs)
  File "/home/amigo/ros/hydro/system/src/challenge_manipulation/src/manipulation.py", line 283, in export_to_pdf
    pdf.items2markdown(placed_items)
  File "/home/amigo/ros/hydro/repos/https:/github.com/tue-robotics/tue_robocup.git/challenge_manipulation/src/pdf.py", line 52, in items2markdown
    md += fmt.format(title=entity.type, path=save_entity_image_to_file(entity.id))
  File "/home/amigo/ros/hydro/repos/https:/github.com/tue-robotics/tue_robocup.git/challenge_manipulation/src/pdf.py", line 36, in save_entity_image_to_file
    info = get_entity_info(entityID)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
ServiceException: service [/ed/gui/get_entity_info] unavailable

**Comment by Rayman** [comment]
You fixed it yourself in 94a176b3806cdae17ab8d0d99a2ac006770e1022
