### ISSUE TITLE
challenge_demo knowledge error

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#439]
Oct 19 11:50:45 amigo2 sudo[21753]: [INFO] [1508406645.059868]: Question: , grammar:
Oct 19 11:50:45 amigo2 sudo[21753]: T[{actions : <A1>}] -> C[A1]
Oct 19 11:50:45 amigo2 sudo[21753]: C[{A}] -> VP[A]
Oct 19 11:50:45 amigo2 sudo[21753]: V_GUIDE -> guide | escort |..
Oct 19 11:50:45 amigo2 sudo[21753]: Traceback (most recent call last):
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/challenge_demo/src/demo.py", line 197, in <module>
Oct 19 11:50:45 amigo2 sudo[21753]:     sys.exit(main())
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/challenge_demo/src/demo.py", line 137, in main
Oct 19 11:50:45 amigo2 sudo[21753]:     target=knowledge.grammar_target)
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 25, in query
Oct 19 11:50:45 amigo2 sudo[21753]:     return self._client.query(description, grammar, target, timeout)
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 98, in query
Oct 19 11:50:45 amigo2 sudo[21753]:     verify_grammar(grammar, target)
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/common.py", line 33, in verify_grammar
Oct 19 11:50:45 amigo2 sudo[21753]:     grammar_parser.verify(target)
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/grammar_parser/src/grammar_parser/cfgparser.py", line 324, in verify
Oct 19 11:50:45 amigo2 sudo[21753]:     self.get_unwrapped(target)
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/grammar_parser/src/grammar_parser/cfgparser.py", line 512, in get_unwrapped
Oct 19 11:50:45 amigo2 sudo[21753]:     unwrapped_string = self.get_unwrapped(conj.name)
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/grammar_parser/src/grammar_parser/cfgparser.py", line 512, in get_unwrapped
Oct 19 11:50:45 amigo2 sudo[21753]:     unwrapped_string = self.get_unwrapped(conj.name)
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/grammar_parser/src/grammar_parser/cfgparser.py", line 512, in get_unwrapped
Oct 19 11:50:45 amigo2 sudo[21753]:     unwrapped_string = self.get_unwrapped(conj.name)
Oct 19 11:50:45 amigo2 sudo[21753]:   File "/home/amigo/ros/kinetic/system/src/grammar_parser/src/grammar_parser/cfgparser.py", line 501, in get_unwrapped
Oct 19 11:50:45 amigo2 sudo[21753]:     raise Exception("Target {} not present in grammar rules".format(lname))
Oct 19 11:50:45 amigo2 sudo[21753]: Exception: Target ROOM_OR_LOCATION not present in grammar rules

**Comment by MatthijsBurgh** [comment]
@SamAlexandrov was 0004bc890060cd7f716a1f4fb2f4376bed9e2571 tested?
