### ISSUE TITLE
[OPEN] missing knowledge.

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#451]
```
[ERROR] [1508874068.219045]: Error raised during SMACH container construction: 
Traceback (most recent call last):

  File "/home/amigo/ros/kinetic/system/src/challenge_open/src/challenge_open.py", line 40, in setup_statemachine
    StartChallengeRobust(robot, challenge_knowledge.initial_pose),

AttributeError: 'module' object has no attribute 'initial_pose'

[ERROR] [1508874068.219536]: Robot exited with <type 'exceptions.AttributeError'>,'module' object has no attribute 'initial_pose',<traceback object at 0x7fa5a4c26b00>
```
```
[ERROR] [1508874301.555514]: Error raised during SMACH container construction: 
Traceback (most recent call last):

  File "/home/amigo/ros/kinetic/system/src/challenge_open/src/challenge_open.py", line 53, in setup_statemachine
    id=challenge_knowledge.ssl_waypoint),

AttributeError: 'module' object has no attribute 'ssl_waypoint'

[ERROR] [1508874301.555838]: Robot exited with <type 'exceptions.AttributeError'>,'module' object has no attribute 'ssl_waypoint',<traceback object at 0x7fc55c8488c0>
```

**Comment by MaxBaeten** [comment]
not necessary since we will remove the open challenge from the test schedule since the current open challenge is depending on HSR and the remaining stuff that is interesting is also in the final.
