### ISSUE TITLE
Fix designator.write([None]) exception

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#873]
```
None [<class 'robot_skills.util.entity.Entity'>]
[ERROR] [1562215087.757899, 747.813000]: InvalidUserCodeError: Could not execute state 'FIND_PEOPLE' of type '<robot_smach_states.human_interaction.find_people_in_room.FindPeople object at 0x7f5d44c8a210>': Traceback (most recent call last):
File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
self._remappings[self._current_label]))
File "/home/rein/dev/tue/src/tue_robocup/robot_smach_states/src/robot_smach_states/human_interaction/find_people_in_room.py", line 187, in execute
self._found_people_designator.write(result_people)
File "/home/rein/dev/tue/src/tue_robocup/robot_smach_states/src/robot_smach_states/util/designators/core.py", line 241, in write
elif isinstance(value, self.variable_designator.resolve_type):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

[ERROR] [1562215087.758699, 747.816000]: State 'WAIT_FOR_CUSTOMER' failed to execute.
[ERROR] [1562215087.759029, 747.816000]: Robot exited with <class 'smach.exceptions.InvalidUserCodeError'>,Could not execute state 'FIND_PEOPLE' of type '<robot_smach_states.human_interaction.find_people_in_room.FindPeople object at 0x7f5d44c8a210>': Traceback (most recent call last):
File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
self._remappings[self._current_label]))
File "/home/rein/dev/tue/src/tue_robocup/robot_smach_states/src/robot_smach_states/human_interaction/find_people_in_room.py", line 187, in execute
self._found_people_designator.write(result_people)
File "/home/rein/dev/tue/src/tue_robocup/robot_smach_states/src/robot_smach_states/util/designators/core.py", line 241, in write
elif isinstance(value, self.variable_designator.resolve_type):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
,<traceback object at 0x7f5d44bed368>
[INFO] [1562215087.759412, 747.816000]: left arm cancelling all goals on all arm-related ACs on close
[INFO] [1562215087.759960, 747.816000]: Torso cancelling all goals on close
Traceback (most recent call last):
File "/home/rein/dev/tue/src/tue_robocup/challenge_restaurant/scripts/challenge_restaurant", line 11, in <module>
startup(challenge_restaurant.restaurant.Restaurant)
File "/home/rein/dev/tue/src/tue_robocup/robot_smach_states/src/robot_smach_states/util/startup.py", line 85, in startup
outcome = executioner.execute()
File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 359, in execute
container_outcome = self._update_once()
File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 250, in _update_once
raise ex
smach.exceptions.InvalidUserCodeError: Could not execute state 'FIND_PEOPLE' of type '<robot_smach_states.human_interaction.find_people_in_room.FindPeople object at 0x7f5d44c8a210>': Traceback (most recent call last):
File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
self._remappings[self._current_label]))
File "/home/rein/dev/tue/src/tue_robocup/robot_smach_states/src/robot_smach_states/human_interaction/find_people_in_room.py", line 187, in execute
self._found_people_designator.write(result_people)
File "/home/rein/dev/tue/src/tue_robocup/robot_smach_states/src/robot_smach_states/util/designators/core.py", line 241, in write
elif isinstance(value, self.variable_designator.resolve_type):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

This happened when `None` was written to a `VariableDesignator(resolve_type[Entity])`

**Comment by LoyVanBeek** [comment]
Writing that should still raise an exception, but a helpful and Designator-specifi one
